Dodecahedr0x/meta-dao-frontend

components/Layout/Layout.tsx
Fixes #9 for external link of the dao page. Also has my default linting.. Sorry.
=> feat: external link to documentation #9

components/Layout/Layout.tsx
nit pick where the favicon wasn't loading.
=> chore: resolves favicon for display

components/Proposals/MarketCard.tsx, components/Proposals/ProposalDetailCard.tsx, hooks/useOpenbookTwap.ts, hooks/useProposal.ts, lib/openbook.ts, lib/types.ts
List orders and enables cancelling, addressing #5 
TODO: Cancelling fails because of invalid ID error
=> Cancel orders

components/Proposals/MarketCard.tsx, contexts/AutocratContext.tsx, hooks/useAutocratDebug.ts, hooks/useInitializeProposal.ts, hooks/useProposal.ts, lib/types.ts, lib/utils.ts
Stores markets and orders in contexts to save RPC calls
=> Reduce requests

components/ManageDao/CreateDaoButton.tsx, components/Markets/ConditionalMarketOrderBook.tsx, components/Proposals/ProposalDetailCard.tsx, components/Proposals/ProposalOrdersCard.tsx
From https://github.com/ansatz-machine/meta-dao-frontend/pull/1
=> hotfix: issue with no bids / asks on one side

components/Markets/ConditionalMarketCard.tsx, components/Markets/ConditionalMarketOrderBook.tsx, components/Proposals/ProposalOrdersCard.tsx, components/Proposals/ProposalOrdersTable.tsx, contexts/AutocratContext.tsx
Fixes (at least partially) #44 and enables settling and closing many orders
=> Refresh on actions

components/Markets/ConditionalMarketCard.tsx, components/Proposals/ProposalDetailCard.tsx, components/Proposals/ProposalOrdersTable.tsx, hooks/useOpenbookTwap.ts, lib/constants.ts, lib/openbookTwap.ts
Add some of the texts proposed in #58
=> Add help texts

hooks/useConditionalVault.ts, hooks/useProposal.ts
This is likely not related to #70 but still fixes the screenshot.
=> fix: check for provider

components/Markets/ConditionalMarketCard.tsx
=> add-crank-market-hog-emoji

components/Proposals/MarketCard.tsx
When betting w/ 100 META
When betting w/ 100 USDC
=> fix #45: issue with help text on the summary proposal page

app/proposals/page.tsx, components/Markets/ConditionalMarketOrderBook.tsx, components/Proposals/ProposalDetailCard.tsx, contexts/AutocratContext.tsx, hooks/useConditionalVault.ts, hooks/useProposal.ts, lib/openbookTwap.ts, lib/types.ts, yarn.lock
- Enables claiming tokens
- Displays a nice number for the spread
- Fixes some bugs on localnet
=> Claim tokens

hooks/useConditionalVault.ts
Create token accounts on redemption. Thanks to `createAssociatedTokenAccountIdempotentInstruction`, this only has an effect if the account does not already exist.
Solves issue #70
=> Create token accounts on settlements

components/Layout/Layout.tsx, hooks/useNetworkConfiguration.ts
=> Prevent crash with bad custom RPC

components/Proposals/ProposalDetailCard.tsx
Not only we need to wait for the proposal to be old enough, TWAPs and markets also have age limits
=> Take maximum delay for countdown

contexts/ProposalContext.tsx
Orders weren't showing because of that.
=> fix: add proposal in useCallback dependencies

components/Proposals/ProposalDetailCard.tsx, components/Providers/Providers.tsx, lib/constants.ts, lib/idl/autocrat_v0.json, lib/idl/autocrat_v0.ts
The downside of this is that we can't see old proposals. Feels worth it.
To address #115
=> Update UI to reflect for new autocrat program

components/Proposals/ProposalDetailCard.tsx, components/Proposals/ProposalList.tsx, contexts/AutocratContext.tsx, lib/constants.ts, lib/idl/autocrat_v0.1.json, lib/idl/autocrat_v0.1.ts, lib/instructions/autocrat.ts, lib/types.ts
Enables switching between program versions
=> Enable multiple programs

hooks/useOpenbookTwap.ts
=> fix: adds account creation on settle.

app/debug/page.tsx, app/page.tsx, components/ManageDao/TransferTokensButton.tsx, components/Proposals/CreateProposalCard.tsx, components/Proposals/ProposalDetailCard.tsx, components/Providers/Providers.tsx, contexts/AutocratContext.tsx, contexts/ProposalContext.tsx, hooks/useNetworkConfiguration.ts, hooks/useOpenbookTwap.ts, hooks/useTokens.ts, lib/instructions/autocrat.ts, lib/instructions/index.ts, lib/instructions/solana.ts, lib/instructions/spl.ts, lib/types.ts, lib/utils.ts
=> Create token transfer proposal

.github/workflows/nextjs.yml, .github/workflows/test-build.yml, app/proposal/page.tsx, components/Markets/ConditionalMarketCard.tsx, components/Orders/UnsettledOrderRow.tsx, components/Orders/UnsettledOrdersTab.tsx, components/Proposals/CreateProposalCard.tsx, components/Proposals/MarketCard.tsx, components/Proposals/MintConditionalTokenCard.tsx, contexts/BalancesContext.tsx, hooks/useBalance.ts, hooks/useInitializeProposal.ts, hooks/useTokenAmount.ts
This context enables synchronizing balances across the UI so that, e.g. newly minted tokens are immediately visible in the orderbook card.
It also fixes the creation of new proposal.
=> Introduce balances context

contexts/ProposalContext.tsx
See here:
https://github.com/metaDAOproject/openbook-twap/blob/master/programs/openbook-twap/src/lib.rs#L84
=> Spread % to match TWAP % orientation
